name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/documentdb:latest . -f .devcontainer/Dockerfile
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/documentdb:latest

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name termsmonitor-documentdb \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/documentdb:latest \
            --ip-address Public \
            --os-type Linux \
            --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label termsmonitor-documentdb \
            --azure-file-volume-account-name termsmonitor \
            --azure-file-volume-account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --azure-file-volume-share-name termsmonitor \
            --azure-file-volume-mount-path /home/documentdb/code \
            --ports 9712 5432
            --command-line "/bin/bash"
